// Generated by CoffeeScript 1.9.0

/*
  @author Takahiro INOUE <takahiro.inoue@aist.go.jp>
  @license Chrome Extension Example for Songle Widget
  ----
  Visit http://songle.jp/info/Credit.html OR http://widget.songle.jp/docs/v1 for documentation.
  Copyright (c) 2015 National Institute of Advanced Industrial Science and Technology (AIST)

  Distributed under the terms of the MIT license only for non-commercial purposes.
  http://www.opensource.org/licenses/mit-license.html

  This notice shall be included in all copies or substantial portions of this Songle Widget API.
  If you are interested in commercial use of Songle Widget API, please contact "songle-ml@aist.go.jp".
 */

(function() {
  addEventListener("load", function() {
    return SongleWidgetAPI.embedSongleWidget({
      snapMode: "bottom-right",
      snapMarginX: 5,
      snapMarginY: 5,
      useSongSearchUI: true,
      api: "chrome-extension-example-for-songle-widget",
      url: "http://www.youtube.com/watch?v=PqJNc9KVIZE",
      onReady: function(songleWidget) {
        return songleWidget.on("beatPlay", function(e) {
          if (e.beat.position % 2 === 0) {
            return $("img").css({
              transform: "rotate(+10deg)"
            });
          } else {
            return $("img").css({
              transform: "rotate(-10deg)"
            });
          }
        });
      }
    });
  }, false);

}).call(this);
